AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  senor-pink-telegram-bot

  A serverless function that listens to webhooks from telegram bot/server

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    MemorySize: 128

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  TelegramBot:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: telegram_bot/
      Handler: app.lambda_handler
      Runtime: python3.10
      Timeout: 60
      Environment:
        Variables:
          TABLE_NAME: milk
      Policies:
        - DynamoDBCrudPolicy:
            TableName: milk
      Architectures:
      - x86_64
      Events:
        TelegramServiceAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /message
            Method: post
  MilkRecords:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: milk
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: Hash
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
