AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  senor-pink-telegram-bot

  A serverless function that listens to webhooks from telegram bot/server

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    MemorySize: 128

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON

Resources:
  TelegramBot:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Connectors:
      MyConn:
        Properties:
          Destination:
            Id: FeedingRecords
          Permissions:
            - Read
            - Write
    Properties:
      CodeUri: telegram_bot/
      Handler: app.lambda_handler
      Runtime: python3.10
      Timeout: 60
      Environment:
        Variables: # Environment Variables: https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html#configuration-envvars-sam
          TABLE_NAME: !Ref FeedingRecords
          ENV: PROD
      Architectures:
      - x86_64
      Events:
        TelegramServiceAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /message
            Method: post
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: BOT_TOKEN
            # Policy to allow AWS Lambda function to read from Parameter Store
            # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
            # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-template-list.html#ssm-parameter-read-policy
            # https://stackoverflow.com/questions/53361664/aws-sam-managed-policy-for-ssm-get-parameter
      Layers:
        - arn:aws:lambda:ap-southeast-2:665172237481:layer:AWS-Parameters-and-Secrets-Lambda-Extension:11
        # AWS Parameters and Secrets Lambda Extension
        # https://docs.aws.amazon.com/systems-manager/latest/userguide/ps-integration-lambda-extensions.html
        # https://community.aws/posts/parameters-and-secrets-lambda-extension-with-python
        # https://docs.aws.amazon.com/secretsmanager/latest/userguide/retrieving-secrets_lambda.html#retrieving-secrets_lambda_ARNs

  FeedingRecords:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: feedings
      AttributeDefinitions:
      - AttributeName: date
        AttributeType: S
      - AttributeName: timestamp
        AttributeType: S
      # https://aws.amazon.com/blogs/database/choosing-the-right-dynamodb-partition-key/
      KeySchema:
        - AttributeName: date
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TelegramBotApi:
    Description: API Gateway endpoint URL for Prod stage for Telegram Bot Lambda Function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/message/"
  TelegramBot:
    Description: Telegram Bot Lambda Function ARN
    Value: !GetAtt TelegramBot.Arn
  FeedingRecords:
    Description: DynamoDB that keeps records.
    Value: !GetAtt FeedingRecords.Arn
