AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  senor-pink-telegram-bot

  A serverless function that listens to webhooks from telegram bot/server

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    MemorySize: 128

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  TelegramBot:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Connectors:
      MyConn:
        Properties:
          Destination:
            Id: FeedingRecords
          Permissions:
            - Read
            - Write
    Properties:
      CodeUri: telegram_bot/
      Handler: app.lambda_handler
      Runtime: python3.10
      Timeout: 60
      Environment:
        Variables:
          TABLE_NAME: !Ref FeedingRecords
          ENV: PROD
      Architectures:
      - x86_64
      Events:
        TelegramServiceAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /message
            Method: post
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: BOT_TOKEN
      Layers:
        - arn:aws:lambda:ap-southeast-2:665172237481:layer:AWS-Parameters-and-Secrets-Lambda-Extension:11
  FeedingRecords:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: feeds
      AttributeDefinitions:
      - AttributeName: date
        AttributeType: S
      KeySchema:
        - AttributeName: date
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TelegramBotApi:
    Description: API Gateway endpoint URL for Prod stage for Telegram Bot Lambda Function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/message/"
  TelegramBot:
    Description: Telegram Bot Lambda Function ARN
    Value: !GetAtt TelegramBot.Arn
  FeedingRecords:
    Description: DynamoDB that keeps records.
    Value: !GetAtt FeedingRecords.Arn
